//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotePLC.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemotePLC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 在线帮助 的本地化字符串。
        /// </summary>
        public static string IDS_ABOUT {
            get {
                return ResourceManager.GetString("IDS_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string IDS_ADD {
            get {
                return ResourceManager.GetString("IDS_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC远程调试助手1.0（天津通广集团数字实验室出品 http://iem.dtvlab.cn） 的本地化字符串。
        /// </summary>
        public static string IDS_APPNAME {
            get {
                return ResourceManager.GetString("IDS_APPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string IDS_CONNECT {
            get {
                return ResourceManager.GetString("IDS_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接测试 的本地化字符串。
        /// </summary>
        public static string IDS_CONNECTION_TEST {
            get {
                return ResourceManager.GetString("IDS_CONNECTION_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string IDS_DELETE {
            get {
                return ResourceManager.GetString("IDS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部删除 的本地化字符串。
        /// </summary>
        public static string IDS_DELETEALL {
            get {
                return ResourceManager.GetString("IDS_DELETEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开 的本地化字符串。
        /// </summary>
        public static string IDS_DISCONNECT {
            get {
                return ResourceManager.GetString("IDS_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTU IP 地址 的本地化字符串。
        /// </summary>
        public static string IDS_DTUIP {
            get {
                return ResourceManager.GetString("IDS_DTUIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_DESC {
            get {
                return ResourceManager.GetString("IDS_HEADER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTU IP 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_DTUIP {
            get {
                return ResourceManager.GetString("IDS_HEADER_DTUIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTU PORT 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_DTUPORT {
            get {
                return ResourceManager.GetString("IDS_HEADER_DTUPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTU SN 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_DTUSN {
            get {
                return ResourceManager.GetString("IDS_HEADER_DTUSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_DTUVER {
            get {
                return ResourceManager.GetString("IDS_HEADER_DTUVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线状态 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_ONLINESTATE {
            get {
                return ResourceManager.GetString("IDS_HEADER_ONLINESTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC品牌 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_PLCBRAND {
            get {
                return ResourceManager.GetString("IDS_HEADER_PLCBRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC型号 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_PLCMODEL {
            get {
                return ResourceManager.GetString("IDS_HEADER_PLCMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行状态 的本地化字符串。
        /// </summary>
        public static string IDS_HEADER_RUNNINGSTATE {
            get {
                return ResourceManager.GetString("IDS_HEADER_RUNNINGSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTU： 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_DTU {
            get {
                return ResourceManager.GetString("IDS_LABEL_DTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本机IP： 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_LOCALIP {
            get {
                return ResourceManager.GetString("IDS_LABEL_LOCALIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口： 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_SERIALPORT {
            get {
                return ResourceManager.GetString("IDS_LABEL_SERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端口： 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_SERVICEPORT {
            get {
                return ResourceManager.GetString("IDS_LABEL_SERVICEPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态： 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_STATUS {
            get {
                return ResourceManager.GetString("IDS_LABEL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC IP 地址 的本地化字符串。
        /// </summary>
        public static string IDS_PLCIP {
            get {
                return ResourceManager.GetString("IDS_PLCIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC端口 的本地化字符串。
        /// </summary>
        public static string IDS_PLCPORT {
            get {
                return ResourceManager.GetString("IDS_PLCPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.请选择一个DTU设备。 的本地化字符串。
        /// </summary>
        public static string IDS_PROMPT01 {
            get {
                return ResourceManager.GetString("IDS_PROMPT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.请选择一个虚拟串口。 的本地化字符串。
        /// </summary>
        public static string IDS_PROMPT02COM {
            get {
                return ResourceManager.GetString("IDS_PROMPT02COM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.请设置目标PLC的IP地址和端口。 的本地化字符串。
        /// </summary>
        public static string IDS_PROMPT02NET {
            get {
                return ResourceManager.GetString("IDS_PROMPT02NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC远程调试助手 的本地化字符串。
        /// </summary>
        public static string IDS_PROMPT03 {
            get {
                return ResourceManager.GetString("IDS_PROMPT03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string IDS_REFRESH {
            get {
                return ResourceManager.GetString("IDS_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口号 的本地化字符串。
        /// </summary>
        public static string IDS_SERIALPORT {
            get {
                return ResourceManager.GetString("IDS_SERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string IDS_SETUP {
            get {
                return ResourceManager.GetString("IDS_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网口 的本地化字符串。
        /// </summary>
        public static string IDS_TABHEADER_NETPORT {
            get {
                return ResourceManager.GetString("IDS_TABHEADER_NETPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口 的本地化字符串。
        /// </summary>
        public static string IDS_TABHEADER_SERIALPORT {
            get {
                return ResourceManager.GetString("IDS_TABHEADER_SERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用手册 的本地化字符串。
        /// </summary>
        public static string IDS_USERMANUAL {
            get {
                return ResourceManager.GetString("IDS_USERMANUAL", resourceCulture);
            }
        }
    }
}
